// GENERATED by code/scripts/gen_bridge.py from ui-schema/bridge.json — DO NOT EDIT.
// The Bridge GATT parse/pack the SPA imports; asserted against ui-schema/bridge-golden.json
// by the Node parity test. Edit the schema + rerun the generator, never this file.
export const PROTO_VER = 1;

function readStr(dv, off, len) {
  let s = ''; for (let i = 0; i < len; i++) { const c = dv.getUint8(off + i); if (!c) break; s += String.fromCharCode(c); } return s;
}
function writeStr(bytes, off, len, s) {
  for (let i = 0; i < len; i++) bytes[off + i] = i < s.length ? s.charCodeAt(i) & 0xff : 0;
}

export function parseStatus(dv) {
  const o = {};
  { const b = dv.getUint8(1); o.flags = {srcConnected: !!(b & 1), outAdvertising: !!(b & 2), recording: !!(b & 4), srcIsAnt: !!(b & 8), outIsAnt: !!(b & 16)}; }
  o.srcPowerW = dv.getInt16(2, true);
  o.outPowerW = dv.getInt16(4, true);
  o.cadenceRpm = dv.getInt16(6, true);
  o.balancePct = dv.getInt8(8);
  o.batteryPct = dv.getUint8(9);
  o.scale = dv.getUint16(10, true) / 1000;
  o.offset = dv.getInt16(12, true) / 10;
  o.recSamples = dv.getUint32(14, true);
  o.uptimeS = dv.getUint16(18, true);
  return o;
}

export function packStatus(o) {
  const bytes = new Uint8Array(20);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = ((o.flags && o.flags.srcConnected) ? 1 : 0) | ((o.flags && o.flags.outAdvertising) ? 2 : 0) | ((o.flags && o.flags.recording) ? 4 : 0) | ((o.flags && o.flags.srcIsAnt) ? 8 : 0) | ((o.flags && o.flags.outIsAnt) ? 16 : 0);
  dv.setInt16(2, o.srcPowerW || 0, true);
  dv.setInt16(4, o.outPowerW || 0, true);
  dv.setInt16(6, o.cadenceRpm || 0, true);
  dv.setInt8(8, o.balancePct || 0);
  bytes[9] = (o.batteryPct || 0) & 0xff;
  dv.setUint16(10, Math.round((o.scale || 0) * 1000), true);
  dv.setInt16(12, Math.round((o.offset || 0) * 10), true);
  dv.setUint32(14, (o.recSamples >>> 0), true);
  dv.setUint16(18, (o.uptimeS || 0) & 0xffff, true);
  return bytes;
}

export function parseConfig(dv) {
  const o = {};
  { const b = dv.getUint8(1); o.flags = {srcIsAnt: !!(b & 1), outIsAnt: !!(b & 2), singleSided: !!(b & 4), spoof: !!(b & 8)}; }
  o.scale = dv.getUint16(2, true) / 1000;
  o.offset = dv.getInt16(4, true) / 10;
  o.srcFilter = readStr(dv, 6, 19);
  o.outName = readStr(dv, 25, 19);
  return o;
}

export function packConfig(o) {
  const bytes = new Uint8Array(44);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = ((o.flags && o.flags.srcIsAnt) ? 1 : 0) | ((o.flags && o.flags.outIsAnt) ? 2 : 0) | ((o.flags && o.flags.singleSided) ? 4 : 0) | ((o.flags && o.flags.spoof) ? 8 : 0);
  dv.setUint16(2, Math.round((o.scale || 0) * 1000), true);
  dv.setInt16(4, Math.round((o.offset || 0) * 10), true);
  writeStr(bytes, 6, 19, o.srcFilter || '');
  writeStr(bytes, 25, 19, o.outName || '');
  return bytes;
}

export function parseButtons(dv) {
  const o = {};
  o.enabled = !!dv.getUint8(1);
  o.act = [dv.getUint8(2), dv.getUint8(3), dv.getUint8(4), dv.getUint8(5), dv.getUint8(6), dv.getUint8(7)];
  return o;
}

export function packButtons(o) {
  const bytes = new Uint8Array(8);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = o.enabled ? 1 : 0;
  bytes[2] = ((o.act||[])[0] || 0) & 0xff;
  bytes[3] = ((o.act||[])[1] || 0) & 0xff;
  bytes[4] = ((o.act||[])[2] || 0) & 0xff;
  bytes[5] = ((o.act||[])[3] || 0) & 0xff;
  bytes[6] = ((o.act||[])[4] || 0) & 0xff;
  bytes[7] = ((o.act||[])[5] || 0) & 0xff;
  return bytes;
}

export function parseRecState(dv) {
  const o = {};
  o.state = dv.getUint8(1);
  o.rateHz = dv.getUint8(2);
  o.reserved = dv.getUint8(3);
  o.samples = dv.getUint32(4, true);
  o.capacity = dv.getUint32(8, true);
  return o;
}

export function packRecState(o) {
  const bytes = new Uint8Array(12);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = (o.state || 0) & 0xff;
  bytes[2] = (o.rateHz || 0) & 0xff;
  bytes[3] = (o.reserved || 0) & 0xff;
  dv.setUint32(4, (o.samples >>> 0), true);
  dv.setUint32(8, (o.capacity >>> 0), true);
  return bytes;
}

export function parseCalState(dv) {
  const o = {};
  o.state = dv.getUint8(1);
  o.reserved = dv.getUint8(2);
  o.pairCount = dv.getUint16(3, true);
  o.minPairs = dv.getUint16(5, true);
  o.residual = dv.getInt16(7, true) / 10;
  o.coverage = [dv.getUint8(9), dv.getUint8(10), dv.getUint8(11), dv.getUint8(12), dv.getUint8(13), dv.getUint8(14)];
  o.enoughToFit = !!dv.getUint8(15);
  return o;
}

export function packCalState(o) {
  const bytes = new Uint8Array(16);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = (o.state || 0) & 0xff;
  bytes[2] = (o.reserved || 0) & 0xff;
  dv.setUint16(3, (o.pairCount || 0) & 0xffff, true);
  dv.setUint16(5, (o.minPairs || 0) & 0xffff, true);
  dv.setInt16(7, Math.round((o.residual || 0) * 10), true);
  bytes[9] = ((o.coverage||[])[0] || 0) & 0xff;
  bytes[10] = ((o.coverage||[])[1] || 0) & 0xff;
  bytes[11] = ((o.coverage||[])[2] || 0) & 0xff;
  bytes[12] = ((o.coverage||[])[3] || 0) & 0xff;
  bytes[13] = ((o.coverage||[])[4] || 0) & 0xff;
  bytes[14] = ((o.coverage||[])[5] || 0) & 0xff;
  bytes[15] = o.enoughToFit ? 1 : 0;
  return bytes;
}

export function parseWkState(dv) {
  const o = {};
  { const b = dv.getUint8(1); o.flags = {loaded: !!(b & 1), running: !!(b & 2), paused: !!(b & 4), ergConnected: !!(b & 8), ergControlled: !!(b & 16)}; }
  o.targetW = dv.getInt16(2, true);
  o.segIndex = dv.getUint8(4);
  o.nSeg = dv.getUint8(5);
  o.segRemainS = dv.getUint16(6, true);
  o.ergSentW = dv.getInt16(8, true);
  o.elapsedS = dv.getUint16(10, true);
  o.biasW = dv.getInt16(12, true);
  o.reserved = dv.getUint32(14, true);
  return o;
}

export function packWkState(o) {
  const bytes = new Uint8Array(18);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = ((o.flags && o.flags.loaded) ? 1 : 0) | ((o.flags && o.flags.running) ? 2 : 0) | ((o.flags && o.flags.paused) ? 4 : 0) | ((o.flags && o.flags.ergConnected) ? 8 : 0) | ((o.flags && o.flags.ergControlled) ? 16 : 0);
  dv.setInt16(2, o.targetW || 0, true);
  bytes[4] = (o.segIndex || 0) & 0xff;
  bytes[5] = (o.nSeg || 0) & 0xff;
  dv.setUint16(6, (o.segRemainS || 0) & 0xffff, true);
  dv.setInt16(8, o.ergSentW || 0, true);
  dv.setUint16(10, (o.elapsedS || 0) & 0xffff, true);
  dv.setInt16(12, o.biasW || 0, true);
  dv.setUint32(14, (o.reserved >>> 0), true);
  return bytes;
}

export function parseCurve(dv) {
  const o = {};
  { const n = dv.getUint8(1); const arr = []; let p = 2;
    for (let i = 0; i < n; i++) { const it = {};
      it.powerW = dv.getUint16(p + 0, true);
      it.factor = dv.getUint16(p + 2, true) / 1000;
      arr.push(it); p += 4; }
    o.points = arr; }
  return o;
}

export function packCurve(o) {
  const items = o.points || [];
  const bytes = new Uint8Array(2 + items.length * 4);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = items.length;
  let p = 2;
  for (const it of items) {
    dv.setUint16(p + 0, (it.powerW || 0) & 0xffff, true);
    dv.setUint16(p + 2, Math.round((it.factor || 0) * 1000), true);
    p += 4; }
  return bytes;
}

export function parseScanList(dv) {
  const o = {};
  { const n = dv.getUint8(1); const arr = []; let p = 2;
    for (let i = 0; i < n; i++) { const it = {};
      it.name = readStr(dv, p + 0, 19);
      it.rssi = dv.getInt8(p + 19);
      { const b = dv.getUint8(p + 20); it.flags = {isCps: !!(b & 1), isFtms: !!(b & 2), isStagesCrank: !!(b & 4)}; }
      arr.push(it); p += 21; }
    o.entries = arr; }
  return o;
}

export function packScanList(o) {
  const items = o.entries || [];
  const bytes = new Uint8Array(2 + items.length * 21);
  const dv = new DataView(bytes.buffer);
  bytes[0] = 1;
  bytes[1] = items.length;
  let p = 2;
  for (const it of items) {
    writeStr(bytes, p + 0, 19, it.name || '');
    dv.setInt8(p + 19, it.rssi || 0);
    bytes[p + 20] = ((it.flags && it.flags.isCps) ? 1 : 0) | ((it.flags && it.flags.isFtms) ? 2 : 0) | ((it.flags && it.flags.isStagesCrank) ? 4 : 0);
    p += 21; }
  return bytes;
}
